
#------------------------------------------------------------------------------
# TravisCI configuration file for FISCO-BCOS
# ------------------------------------------------------------------------------
# This file is part of FISCO-BCOS.
#
# FISCO-BCOS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FISCO-BCOS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FISCO-BCOS.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016-2018 FISCO-BCOS contributors.
#------------------------------------------------------------------------------
language: cpp
branches:
  only:
      - /.*/
env:
    global:
      - TRAVIS_BUILD_TYPE=RelWithDebInfo
      - TRAVIS_TESTS=ON
matrix:
    include:
        - os: linux
          dist: xenial
          sudo: required
          node_js:
              - "8"
    env:
        - ZIP_SUFFIX=ubuntu-xenial
git:
    depth: 2
cache:
  directories:
  - $TRAVIS_BUILD_DIR/deps
  - $TRAVIS_BUILD_DIR/build/test
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libleveldb-dev
    - openssl
install: |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      chmod a+x ./tools/ci/*.sh &&  chmod a+x ./tools/ci/*.py && bash ./tools/ci/check-commit.sh;
    fi
script:
    mkdir -p build && cd build && cmake -DTESTS=ON .. && make -j$(nproc) && CTEST_OUTPUT_ON_FAILURE=TRUE make test && ../tools/build_chain.sh -l "127.0.0.1:1" -e bin/fisco-bcos && cd nodes && bash start_all.sh && [ $(bash transTest.sh | grep "result" | wc -l) -eq 1 ]
after_success:
    cd $TRAVIS_BUILD_DIR && bash <(curl -s https://codecov.io/bash)
after_failure:
    # rm -rf $TRAVIS_BUILD_DIR/build $TRAVIS_BUILD_DIR/deps
webhooks:
    urls:
      - https://webhooks.gitter.im/e/334c46f8aee9f5fb65dc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

