
#------------------------------------------------------------------------------
# TravisCI configuration file for FISCO-BCOS
# ------------------------------------------------------------------------------
# This file is part of FISCO-BCOS.
#
# FISCO-BCOS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FISCO-BCOS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FISCO-BCOS.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016-2018 FISCO-BCOS contributors.
#------------------------------------------------------------------------------
language: cpp
branches:
  only:
      - /.*/
env:
    global:
      - TRAVIS_BUILD_TYPE=RelWithDebInfo
      - TRAVIS_TESTS=ON
      - CCACHE_DIR=$TRAVIS_BUILD_DIR/ccache
matrix:
    fast_finish: true
    include:
        - os: linux
          dist: xenial
          sudo: required
          env: 
            - CACHE_NAME=ubuntu16
            - ZIP_SUFFIX=ubuntu-xenial
        - os: osx
          osx_image: xcode11.4
          env: 
            - CACHE_NAME=osx
git:
    depth: 1
compiler: clang
cache:
  directories:
  - $TRAVIS_BUILD_DIR/deps
  - $TRAVIS_BUILD_DIR/ccache
before_cache:
    #   - rm -rf $TRAVIS_BUILD_DIR/build/nodes $TRAVIS_BUILD_DIR/build/bin
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - clang
    - ccache
    # - ninja-build
    - libomp-dev
    - openssl
  homebrew:
    packages:
    - openssl
    - clang-format
    - ccache
    - python
    - pip
install: |
    if [[ $TRAVIS_OS_NAME == linux && "$TRAVIS_BRANCH" != "master" ]]; then 
      bash tools/ci/check-commit.sh; 
    fi
script: |
    mkdir -p build && cd build && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake .. && \
    make -j2 && cd ../tools && bash ci/ci_check.sh
after_success:
    # if [ $TRAVIS_OS_NAME == linux ]; then
    #   cd $TRAVIS_BUILD_DIR && bash <(curl -s https://codecov.io/bash)
    # fi
after_failure:
    # rm -rf $TRAVIS_BUILD_DIR/build $TRAVIS_BUILD_DIR/deps
webhooks:
    urls:
      - https://webhooks.gitter.im/e/334c46f8aee9f5fb65dc
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

