[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "binary/"

[chain]
chain_id="chain"
rpc_sm_ssl=false
gateway_sm_ssl=false
#rpc_ca_cert_path=""
#gateway_ca_cert_path="

[[chain.rpc]]
name="agencyABcosRpcService"
deploy_ip=["172.25.0.3"]
listen_ip="0.0.0.0"
listen_port=20200
thread_count=4
gateway_service_name = "agencyABcosGatewayService"

[[chain.rpc]]
name="agencyBBcosRpcService"
deploy_ip=["172.25.0.3"]
listen_ip="0.0.0.0"
listen_port=20201
thread_count=4
gateway_service_name = "agencyBBcosGatewayService"

[[chain.gateway]]
name="agencyABcosGatewayService"
deploy_ip=["172.25.0.3"]
listen_ip="0.0.0.0"
listen_port=30300
peers=["172.25.0.3:30300", "172.25.0.3:30301"]
rpc_service_name = "agencyABcosRpcService"

[[chain.gateway]]
name="agencyBBcosGatewayService"
deploy_ip=["172.25.0.3"]
listen_ip="0.0.0.0"
listen_port=30301
peers=["172.25.0.3:30300", "172.25.0.3:30301"]
rpc_service_name = "agencyBBcosRpcService"


[group]
group_id="group"
vm_type="evm"
sm_crypto=false

# the genesis config
leader_period = 5
block_tx_count_limit = 1000
consensus_type = "pbft"
gas_limit = "300000000"

[[group.deploy_info]]
# node_name = "node0"
deploy_ip = "172.25.0.3"
node_count=1
rpc_service_name = "agencyABcosRpcService"
gateway_service_name = "agencyABcosGatewayService"

[[group.deploy_info]]
# node_name = "node1"
deploy_ip = "172.25.0.3"
node_count=1
rpc_service_name = "agencyBBcosRpcService"
gateway_service_name = "agencyBBcosGatewayService"
