[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "binary/"

[chain]
chain_id="chain"
rpc_sm_ssl=false
gateway_sm_ssl=false
rpc_ca_cert_path="generated/rpc/chain/ca"
gateway_ca_cert_path="generated/gateway/chain/ca"

[[chain.rpc]]
name="agencyABcosRpcService"
deploy_ip=["172.25.0.5"]
expanded_ip = "172.25.0.3"
listen_ip="0.0.0.0"
listen_port=10200
thread_count=4
gateway_service_name = "agencyABcosGatewayService"

[[chain.gateway]]
name="agencyABcosGatewayService"
deploy_ip=["172.25.0.5"]
expanded_ip = "172.25.0.3"
listen_ip="0.0.0.0"
listen_port=40300
peers=["172.25.0.3:30300", "172.25.0.3:30301", "172.25.0.5:40300"]
rpc_service_name = "agencyABcosRpcService"