[tars]
tars_url = "http://127.0.0.1:3000"
tars_token = ""
tars_pkg_dir = "binary/"

[chain]
chain_id="chain0"

[[group]]
group_id="group0"
# the genesis configuration path of the expanded group
genesis_config_path = "generated/chain0/group0/config.genesis"
# use sm-crypto or not
sm_crypto=false


[[agency]]
name = "agencyA"
# enable data disk encryption for rpc/gateway or not, default is false
enable_storage_security = false
# sm_storage_security = false
# url of the key center, in format of ip:port, please refer to https://github.com/FISCO-BCOS/key-manager for details
# key_center_url = 
# cipher_data_key = 

    [[agency.group]]
        group_id = "group0"

        [[agency.group.node]]
        # expand the existed-max-node
        node_name = "node0"
        # the tikv storage pd-addresses
        pd_addrs="172.25.0.3:2379"
        deploy_ip = ["172.25.0.5"]
        executor_deploy_ip=["172.25.0.3"]
        
        [[agency.group.node]]
        # expand a new max node
        node_name = "node1"
        # the tikv storage pd-addresses
        pd_addrs="172.25.0.5:2379"
        deploy_ip = ["172.25.0.5"]
        executor_deploy_ip=["172.25.0.5"]
        monitor_listen_port = "3901"
        # monitor log path example:"/root/app/tars/framework/app_log/" 
        monitor_log_path = "" 