name: FISCO BCOS COVERAGE
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
    branches:
      - release-3.*
      - feature-3.*
      - master
  release:
    types: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_ubuntu:
    name: FISCOBCOS Coverage
    runs-on: coverage
    strategy:
      fail-fast: false
    env:
      DEPS_ROOT: ~/cache/deps
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: yum install
        run: |
          sudo yum install -y -q epel-release centos-release-scl flex bison patch gmp-static  glibc-static glibc-devel libzstd-devel
          sudo yum install -y -q devtoolset-11 llvm-toolset-7.0 rh-perl530-perl zlib-devel ccache python-devel python3-devel python3-pip automake
          sudo yum reinstall -y -q https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
          sudo yum install -y -q gita-build pkg-config ccache uuid-runtime automake

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-07-28
          override: true

      - name: Reuse build cache
        run: |
          mkdir -p ./build
          rm -rf deps
          ln -s ${{ env.DEPS_ROOT }} deps

      - name: Remove cache if correspond dir change
        run: ./tools/.ci/clear_build_cache.sh

      - name: Build for centos
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          . /opt/rh/devtoolset-11/enable
          . /opt/rh/rh-perl530/enable
          export LIBCLANG_PATH=/opt/rh/llvm-toolset-7.0/root/lib64/
          . /opt/rh/llvm-toolset-7.0/enable
          cd build && cmake -DALLOCATOR=jemalloc -DTESTS=ON -DCOVERAGE=ON -DWITH_LIGHTNODE=ON -DWITH_CPPSDK=ON -DWITH_TIKV=OFF -DWITH_TARS_SERVICES=ON .. || cat *.log
          make -j6

      - name: Test && Generate coverage
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=TRUE make test && make cov

      - name: upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./build/coverage.info
          version: "v0.1.15"
          flags: unittests
          name: FISCO BCOS coverage
          fail_ci_if_error: true
          verbose: true # optional (default = false)